### ISSUE TITLE
flist for threebot

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX#757]
generate an flist for 3bot server

**Comment by waleedhammam** [comment]
Implemented build, install, sandbox. Still working on the startup toml

**Comment by waleedhammam** [comment]
fix at lua builder in sandbox: https://github.com/threefoldtech/jumpscaleX/commit/890e6db052de86efdbd03ead19985edb0a749fe2

**Comment by waleedhammam** [comment]
add sonic sandbox: https://github.com/threefoldtech/jumpscaleX/commit/6421bd77307ff3d8c7cdd48be157723e00469714

**Comment by waleedhammam** [comment]
add threebot builder at: https://github.com/threefoldtech/jumpscaleX/commit/fc9d3ecd84cb33876c8e5985e5f0ed53253de348
flist at: https://hub.grid.tf/hammam/threebot.flist.md
still working on the flist fixes

**Comment by waleedhammam** [comment]
add flist tweeks: https://github.com/threefoldtech/jumpscaleX/commit/30b7699a0636cbb590d133bdc5ca2372130f8a76

**Comment by waleedhammam** [comment]
fixed jsx autobuilder at: https://github.com/threefoldtech/jumpscaleX/commit/cadbacf930abed80860504fc848661303a67c3d9 https://github.com/threefoldtech/jumpscaleX/commit/6017d90b6de9a637ca2469da8bd15a2ceece3818  https://github.com/threefoldtech/jumpscaleX/commit/cf05b8238e1011704271ab0b323e5fb18d517c12  https://github.com/threefoldtech/jumpscaleX/commit/ba631ba956c4bb83ebd150aa84b8c1769aa0aece

**Comment by waleedhammam** [comment]
3bot builder at: https://github.com/threefoldtech/jumpscaleX/blob/development_jumpscale/Jumpscale/builders/apps/BuilderThreebot.py
generate flist at: https://hub.grid.tf/hammam/threebot_dev.flist, note you should wait for the flist to be deployed correctly, once it's done you have a ready 3bot container.
working on more tests for the flist and performance improvment

**Comment by Pishoy** [comment]
Am facing this error while testing theebot as below 
```
JSX> j.servers.threebot.test()     
                                                                                                           
no server running on /tmp/tmux-0/default
no server running need to start
++ '[' start == kill ']'
++ tmux -f /sandbox/cfg/.tmux.conf has-session
no server running on /tmp/tmux-0/default
++ '[' 1 -eq 1 ']'
++ echo 'no server running need to start'
++ tmux -f /sandbox/cfg/.tmux.conf new -s main -d 'bash --rcfile /sandbox/bin/env_tmux_detach.sh'
++ '[' start '!=' start ']'
main: 1 windows (created Sun Aug 18 14:14:19 2019) [80x24]
## .startupcmd.1
id: 2
name                : zdb
cmd_start           : zdb --listen 127.0.0.1 --port 9900 --mode seq --admin 123456 --protect
interpreter         : BASH
cmd_stop            : 
debug               : False
path                : /sandbox/var/zdb/threebot/
env                 : {}
ports               :
    - 9,900
ports_udp           : []
timeout             : 10
process_strings     : []
process_strings_regex: []
pid                 : 0
executor            : TMUX
daemon              : True
hardkill            : False
state               : DOWN
corex_client_name   : default
corex_id            : 

error               : 
time_start          : 2019/08/18 14:14:23
time_refresh        : 2019/08/18 14:14:19
time_stop           : 2019/08/18 14:14:21

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/DigitalMe/servers/threebot/ThreeBotServersFactory.py", line 45, in test
    s.start()
  File "/sandbox/lib/jumpscale/DigitalMe/servers/threebot/ThreebotServer.py", line 45, in start
    j.servers.openresty.build()
  File "/sandbox/lib/jumpscale/DigitalMe/servers/openresty/OpenRestyFactory.py", line 42, in build
    j.sal.fs.copyDirTree("/sandbox/openresty/luarocks/bin/resty-auto-ssl/", "/bin", rsyncdelete=False)
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFS.py", line 290, in copyDirTree
    rc, out, err = j.sal.process.execute(cmd, showout=showout)
  File "/sandbox/lib/jumpscale/Jumpscale/sal/process/SystemProcess.py", line 108, in execute
    replace=replace,
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 1899, in execute
    raise Tools.exceptions.Base(msg)
Jumpscale.core.InstallTools.BaseJSException: {RED}EXCEPTION: 

    Could not execute:    rsync --no-owner --no-group -rLt --partial  --exclude '*.egg-info/' --exclude '*.dist-info/'
        --exclude '*__pycache__/'
            '/sandbox/openresty/luarocks/bin/resty-auto-ssl/' '/bin' --verbose

    stdout:
        sending incremental file list

        sent 3,659 bytes  received 32 bytes  7,382.00 bytes/sec
        total size is 1,753,269  speedup is 475.01

    stderr:
        rsync: readlink_stat("/sandbox/openresty/luarocks/bin/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-
        ssl/resty-
            auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-
            ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-
        ssl/resty-
            auto-ssl/resty-auto-ssl/resty-auto-ssl") failed: Too many levels of symbolic links (40)
        rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]{RESET}

{RED}EXCEPTION: 

    Could not execute:    rsync --no-owner --no-group -rLt --partial  --exclude '*.egg-info/' --exclude '*.dist-info/'
        --exclude '*__pycache__/'
            '/sandbox/openresty/luarocks/bin/resty-auto-ssl/' '/bin' --verbose

    stdout:
        sending incremental file list

        sent 3,659 bytes  received 32 bytes  7,382.00 bytes/sec
        total size is 1,753,269  speedup is 475.01

    stderr:
        rsync: readlink_stat("/sandbox/openresty/luarocks/bin/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-
        ssl/resty-
            auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-
            ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-ssl/resty-auto-
        ssl/resty-
            auto-ssl/resty-auto-ssl/resty-auto-ssl") failed: Too many levels of symbolic links (40)
        rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]{RESET}
```
- js version 
```
3BOTDEVEL:3bot:jumpscaleX: git log -1
commit 074d680e3e571388bb268facbb24fcd8d72b56e4 (HEAD -> development_jumpscale, origin/development_jumpscale)
Author: kristof de spiegeleer <>
Date:   Sun Aug 18 14:37:08 2019 +0200

    bug
3BOTDEVEL:
```
